/** @type { import('@storybook/html-vite').StorybookConfig } */
const config = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],

  addons: [
    {
      name: 'storybook-design-token',
      options: {
        preserveCSSVars: true,
      },
    },
    '@storybook/addon-docs',
  ],

  framework: '@storybook/html-vite',

  staticDirs: [
    {
      from: './assets',
      to: '/public',
    },
    // AI-friendly markdown docs (llms.txt + per-page markdown), generated by
    // `yarn build-docs:llms` which runs as part of the storybook scripts.
    {
      from: '../llms-docs',
      to: '/',
    },
  ],

  core: {
    disableTelemetry: true, // 👈 Disables telemetry
  },

  features: {
    backgrounds: false,
  },

  // Vite's default target (chrome111/firefox114/safari16.4) predates
  // light-dark() support, so lightningcss tries to polyfill it and breaks.
  async viteFinal(viteConfig) {
    viteConfig.build ??= {}
    viteConfig.build.cssTarget = ['chrome123', 'edge123', 'firefox120', 'safari17.5', 'ios17.5']
    return viteConfig
  },
}
export default config
