name: Deploy to GHP

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

env:
  GITHUB_PACKAGES_TOKEN: ${{ secrets.ROLEMODEL_PACKAGE_REPO_READ_TOKEN }}

jobs:
  build-gph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com/'
      - run: yarn install --immutable
      - run: yarn build
      - run: npm publish --access public
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}
