# This workflow will do a clean installation of node dependencies, cache/restore them, and run linting

name: Linting CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install
        run: npm install
  lint:
    name: Run Linters
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run ESLint
        run: npm run lint:js
      - name: Run Stylelint
        run: npm run lint:css
      - name: Run Prettier
        run: npm run prettier-check
  build:
    name: Run Build scripts
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build CSS
        run: npm run build:css
      - name: Build SCSS
        run: npm run build:scss
      - name: Build Tokens
        run: npm run build:tokens
      - name: Build Storybook
        run: npm run build-storybook
